language: node_js
node_js:
  - "7"
cache: yarn
before_script:
 - sh login.sh
 - "echo \"doing a patch update!\""
 - "git config --global user.email \"noreply@quran.com\""
 - "git config --global user.name \"circleci-qurandev\""
after_script:
  - npm version patch
  - git commit --amend -m 'automated patching [ci skip]'
  - git push
  - npm run deploy:npm
  - npm run deploy:gp
script:
  - node --version
  - yarn --version
  - yarn run test